version: '3.8'

services:
  frontend:
    build:
      context: ./ThreeoFront/threeo-v1
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./ThreeoBack/ThreeoAPI
      dockerfile: Dockerfile
    ports:
      - "8080:80"